version = 4
run_type = "staged_learning"
use_cuda = true
output_csv = "/home/tommyell/outputs/2xch_rl_TL.csv"
tb_logdir = "/home/tommyell/outputs/2xch_rl_TL"  

[parameters]
use_checkpoint = false  
summary_csv_prefix = "/home/tommyell/outputs/2xch_rl"
agent_file = "/home/tommyell/CANADAINTERNSHIP/reinvent_TL_2xch.model"
prior_file = "/home/tommyell/REINVENT4/priors/reinvent.prior"

batch_size = 128          
uniquify_smiles = true   
randomize_smiles = true  

[learning_strategy]

type = "dap"    
sigma = 128      
rate = 0.0005     

[diversity_filter] 

type = "IdenticalMurckoScaffold" 
bucket_size = 50
minscore = 0.4

[[stage]]
chkpt_file = '/home/tommyell/CANADAINTERNSHIP/rl_direct_TL.chkpt'
termination = "simple"
max_steps = 50

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[[stage.scoring.component.DockStream.endpoint]]
name = "Docking into 2XCH grid"
weight = 1
params.configuration_path = "/home/tommyell/CANADAINTERNSHIP/2xch_docking_config.json"
params.docker_script_path = "/home/tommyell/DockStream/docker.py"
params.docker_python_path =  "/home/tommyell/miniconda3/envs/DockStream/bin/python"
transform.type = "reverse_sigmoid"
transform.high = -7
transform.low = -13.5
transform.k = 0.2

[[stage.scoring.component]]
[stage.scoring.component.QED]
[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 1
