# Transfer learning on a set of related active compounds

run_type = "transfer_learning"
use_cuda = false
tb_logdir = "/home/tommyell/outputs/tb_TL"  

[parameters]

num_epochs = 10
save_every_n_epochs = 5 
batch_size = 50
num_refs = 50  
sample_batch_size = 50  

input_model_file = "/home/tommyell/REINVENT4/priors/reinvent.prior"
smiles_file = "/home/tommyell/CANADAINTERNSHIP/TL_smiles.smi"
output_model_file = "/home/tommyell/CANADAINTERNSHIP/reinvent_TL_2xch.model"
validation_smiles_file = "/home/tommyell/CANADAINTERNSHIP/TL_smiles.smi"
